In [7]:
import os
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
import ants

In [8]:
from glob2 import glob

path_gbm = '/anvar/public_datasets/preproc_study/gbm/orig'
path_bgpd = '/anvar/public_datasets/preproc_study/bgpd/orig'
path_schw = '/anvar/public_datasets/preproc_study/schw/orig'

list_gbm = glob(path_gbm + '/**/CT1_SEG.nii.gz')
list_bgpd = glob(path_bgpd + '/**/mask_GTV_FLAIR.nii.gz')
list_schw = glob(path_schw + '/**/T1_SEG.nii.gz')

In [29]:
# checking orig for right labels
path_gbm = '/anvar/public_datasets/preproc_study/gbm/1_reg'
list_gbm = glob(path_gbm + '/**/CT1_SEG.nii.gz')

for img_path in tqdm(list_gbm):
    img_orig = ants.image_read(img_path)
    channels = np.unique(img_orig.numpy())[1:]
    if channels[0] != 1:
        print(img_path)
        print('weird channels', channels)
        result_arr = img_orig.numpy()
        result_arr[result_arr == channels[0]] = int(1)
        result_arr[result_arr == channels[1]] = int(2)
        result_arr[result_arr == channels[2]] = int(3)
        img_new = img_orig.new_image_like(result_arr)
        print(np.unique(img_new.numpy())[1:])
#         os.remove(img_path)
#         ants.image_write(img_new, img_path, ri=False);

100%|██████████| 102/102 [00:38<00:00,  2.67it/s]


In [30]:
# checking orig for right labels
path_gbm = '/anvar/public_datasets/preproc_study/gbm/4a_resamp'
list_gbm = glob(path_gbm + '/**/CT1_SEG.nii.gz')

for img_path in tqdm(list_gbm):
    img_orig = ants.image_read(img_path)
    channels = np.unique(img_orig.numpy())[1:]
    if channels[0] != 1:
        print(img_path)
        print('weird channels', channels)
        result_arr = img_orig.numpy()
        result_arr[result_arr == channels[0]] = int(1)
        result_arr[result_arr == channels[1]] = int(2)
        result_arr[result_arr == channels[2]] = int(3)
        img_new = img_orig.new_image_like(result_arr)
        print(np.unique(img_new.numpy())[1:])
#         os.remove(img_path)
#         ants.image_write(img_new, img_path, ri=False);

100%|██████████| 102/102 [00:40<00:00,  2.53it/s]


### Check new saved

In [12]:
os.listdir('/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-02-0086')

['T2.nii.gz', 'FLAIR.nii.gz', 'T1.nii.gz', 'CT1_SEG.nii.gz', 'CT1.nii.gz']

In [33]:
mask.shape

(320, 320, 30)

In [14]:
# checking 1_reg for right labels

path_gbm = '/anvar/public_datasets/preproc_study/gbm/4a_reasmp'

for img_path in tqdm(list_gbm):
    img_orig = ants.image_read(img_path)
    channels = np.unique(img_orig.numpy())[1:]
    if channels[0] != 1:
        print(img_path)
        print('weird channels', channels)
        result_arr = img_orig.numpy()
        result_arr[result_arr == channels[0]] = int(1)
        result_arr[result_arr == channels[1]] = int(2)
        result_arr[result_arr == channels[2]] = int(3)
        img_new = img_orig.new_image_like(result_arr)
        print(np.unique(img_new.numpy())[1:])
#         os.remove(img_path)

 19%|█▊        | 19/102 [00:04<00:14,  5.78it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6661/CT1_SEG.nii.gz
weird channels [1.560928 4.682784 6.243712]
[1. 2. 3.]


 46%|████▌     | 47/102 [00:13<00:20,  2.68it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-14-1794/CT1_SEG.nii.gz
weird channels [2.5308914 5.061783  7.5926743]


 47%|████▋     | 48/102 [00:13<00:22,  2.36it/s]

[1. 2. 3.]


 58%|█████▊    | 59/102 [00:19<00:16,  2.58it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6657/CT1_SEG.nii.gz
weird channels [3.2803419 6.5606837 9.841025 ]
[1. 2. 3.]


 61%|██████    | 62/102 [00:19<00:10,  3.72it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6662/CT1_SEG.nii.gz
weird channels [1.8251526 3.6503053 5.475458 ]
[1. 2. 3.]


 70%|██████▉   | 71/102 [00:23<00:14,  2.11it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-4935/CT1_SEG.nii.gz
weird channels [1.4778999 2.9557998 4.4336996]
[1. 2. 3.]


 76%|███████▋  | 78/102 [00:24<00:05,  4.69it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6664/CT1_SEG.nii.gz
weird channels [1.8178266 3.6356533 5.45348  ]
[1. 2. 3.]
/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6663/CT1_SEG.nii.gz
weird channels [ 3.823199  7.646398 11.469597]
[1. 2. 3.]


 78%|███████▊  | 80/102 [00:25<00:04,  5.29it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-4934/CT1_SEG.nii.gz
weird channels [1.524298 3.048596 4.572894]
[1. 2. 3.]


 95%|█████████▌| 97/102 [00:33<00:02,  2.04it/s]

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6656/CT1_SEG.nii.gz
weird channels [1.9323565 3.864713  5.7970695]
[1. 2. 3.]


100%|██████████| 102/102 [00:35<00:00,  2.90it/s]


In [16]:
def check_multiple_channels(path_to_img):
    """check that for Untypical channels, like [ 3.823199  7.646398 11.469597].
    This happens on GBM or LGG datasets, with multichanel target, after registration.
    """
    img = ants.image_read(path_to_img)

    channels = np.unique(img.numpy())[1:]
    if np.shape(channels)[0] > 1:
        if channels[0] != 1:
            print(path_to_img)
            print('Untypical channels', channels)
            result_arr = img.numpy()
            result_arr[result_arr == channels[0]] = int(1)
            result_arr[result_arr == channels[1]] = int(2)
            result_arr[result_arr == channels[2]] = int(3)
            img_new = img.new_image_like(result_arr)
            img = img_new
            channels = [1,2,3]

    return(img , channels)

In [17]:
mask = ants.image_read('/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6656/CT1_SEG.nii.gz')

In [18]:
 channels = np.unique(mask.numpy())[1:]

In [19]:
 channels

array([1.9323565, 3.864713 , 5.7970695], dtype=float32)

In [20]:
mask, ch = check_multiple_channels('/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6656/CT1_SEG.nii.gz')

/anvar/public_datasets/preproc_study/gbm/orig/TCGA-76-6656/CT1_SEG.nii.gz
Untypical channels [1.9323565 3.864713  5.7970695]


In [21]:
np.unique(mask.numpy())[1:]

array([1., 2., 3.], dtype=float32)