In [20]:
import os, sys
import numpy as np
import ants
import argparse
import shutil
import logging
import subprocess
import glob
from tqdm import tqdm
import matplotlib.pyplot as plt 
import pandas as pd

In [24]:
from glob2 import glob

path_gbm = '/anvar/public_datasets/preproc_study/gbm/1_reg'
path_bgpd = '/anvar/public_datasets/preproc_study/bgpd/orig'
path_schw = '/anvar/public_datasets/preproc_study/schw/orig'

list_gbm = glob(path_gbm + '/**/CT1_SEG.nii.gz')
list_bgpd = glob(path_bgpd + '/**/mask_GTV_FLAIR.nii.gz')
list_schw = glob(path_schw + '/**/T1_SEG.nii.gz')

In [26]:
# checking for right labels
import ants

for img_path in tqdm(list_gbm):
    img_orig = ants.image_read(img_path)
    channels = np.unique(img_orig.numpy())[1:]
    if channels[0] != 1:
        print(img_path)
        print('weird channels', channels)
        result_arr = img_orig.numpy()
        result_arr[result_arr == channels[0]] = int(1)
        result_arr[result_arr == channels[1]] = int(2)
        result_arr[result_arr == channels[2]] = int(3)
        img_new = img_orig.new_image_like(result_arr)
        print(np.unique(img_new.numpy())[1:])
#         os.remove(img_path)
#         ants.image_write(img_new, img_path, ri=False);

 19%|█▊        | 19/102 [00:05<00:14,  5.69it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6661/CT1_SEG.nii.gz
weird channels [1.560928 4.682784 6.243712]
[1. 2. 3.]


 46%|████▌     | 47/102 [00:15<00:24,  2.25it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-14-1794/CT1_SEG.nii.gz
weird channels [2.5308914 5.061783  7.5926743]


 47%|████▋     | 48/102 [00:15<00:25,  2.09it/s]

[1. 2. 3.]


 58%|█████▊    | 59/102 [00:21<00:19,  2.21it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6657/CT1_SEG.nii.gz
weird channels [3.2803419 6.5606837 9.841025 ]
[1. 2. 3.]


 61%|██████    | 62/102 [00:22<00:12,  3.29it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6662/CT1_SEG.nii.gz
weird channels [1.8251526 3.6503053 5.475458 ]
[1. 2. 3.]


 70%|██████▉   | 71/102 [00:26<00:16,  1.87it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-4935/CT1_SEG.nii.gz
weird channels [1.4778999 2.9557998 4.4336996]
[1. 2. 3.]


 76%|███████▋  | 78/102 [00:28<00:05,  4.22it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6664/CT1_SEG.nii.gz
weird channels [1.8178266 3.6356533 5.45348  ]
[1. 2. 3.]
/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6663/CT1_SEG.nii.gz
weird channels [ 3.823199  7.646398 11.469597]
[1. 2. 3.]


 78%|███████▊  | 80/102 [00:28<00:04,  4.78it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-4934/CT1_SEG.nii.gz
weird channels [1.524298 3.048596 4.572894]
[1. 2. 3.]


 95%|█████████▌| 97/102 [00:38<00:02,  1.76it/s]

/anvar/public_datasets/preproc_study/gbm/1_reg/TCGA-76-6656/CT1_SEG.nii.gz
weird channels [1.9323565 3.864713  5.7970695]
[1. 2. 3.]


100%|██████████| 102/102 [00:39<00:00,  2.56it/s]
